### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by fryfrog** [asomers/ztop#9]
I wish I was smart enough to *actually* fix and submit a patch, but the best I can do is show you errors.

```
   Compiling ztop v0.1.1 (/home/fryfrog/git/ztop)
error[E0433]: failed to resolve: use of undeclared type `SnapshotIter`
  --> src/app.rs:68:9
   |
68 |         SnapshotIter::new(pool)
   |         ^^^^^^^^^^^^ use of undeclared type `SnapshotIter`

error[E0412]: cannot find type `SnapshotIter` in this scope
  --> src/app.rs:67:47
   |
28 | struct Snapshot {
   | --------------- similarly named struct `Snapshot` defined here
...
67 |     pub fn iter(pool: Option<&str>) -> Result<SnapshotIter, Box<dyn Error>> {
   |                                               ^^^^^^^^^^^^
   |
help: a struct with a similar name exists
   |
67 |     pub fn iter(pool: Option<&str>) -> Result<Snapshot, Box<dyn Error>> {
   |                                               ^^^^^^^^
help: you might be missing a type parameter
   |
38 | impl<SnapshotIter> Snapshot {
   |     ^^^^^^^^^^^^^^

error[E0599]: no associated item named `CLOCK_UPTIME` found for struct `nix::time::ClockId` in the current scope
   --> src/app.rs:111:51
    |
111 |             let boottime = clock_gettime(ClockId::CLOCK_UPTIME).unwrap();
    |                                                   ^^^^^^^^^^^^
    |                                                   |
    |                                                   associated item not found in `nix::time::ClockId`
    |                                                   help: there is an associated constant with a similar name: `CLOCK_BOOTTIME`

Some errors have detailed explanations: E0412, E0433, E0599.
For more information about an error, try `rustc --explain E0412`.
```

Feel free to just close if you don't want this sort of not very helpful help. :)

**Comment by guygastineau** [comment]
@fryfrog these lines in the `app` module intentionally build the freebsd module only when the project is compiled on freebsd. 

 https://github.com/asomers/ztop/blob/b1b0384c636d672da90927da1fc303227f1b73b4/src/app.rs#L17-L22

The `SnapshotIter` struct is defined in that module, so that is why you get the errors.

---

I mostly use Haskell and Lisp, but I don't mind trying my hand at patching this for linux.  I use ZFS with both FreeBSD and Arch Linux, so it would benefit me.  I used to use rust, and I have used it at work; so I can probably get it done.

**Comment by asomers** [comment]
Yes, Linux support is not implemented yet.  I don't use ZoL myself, but I would accept a patch if anybody writes one.  It's probably not too hard; you just need to figure out how to read those statistics counters.

**Comment by guygastineau** [comment]
@asomers oh, thank you for explaining.  I will read the DataSource code more closely then.  Sorry for the misunderstanding.  In my ZoL branch I have made a FromStr instance for Snapshot since sysctl doesn't seem seem to work for getting the stats on Linux.  I will work out how to get this working with the DataSource once I get the Linux backend in place.

**Comment by fryfrog** [comment]
I just checked it out and `cargo build` it and its working great!
